name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full commit history for Gradle

    # Set permissions for Gradle Wrapper
    - name: Set execute permissions
      if: matrix.os != 'windows-latest'
      run: |
        chmod +x gradlew
        ls -la gradlew*  # Verify permissions

    # Verify Gradle
    - name: Verify Gradle
      run: ./gradlew --version

    # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    # Setup Gradle with caching
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false
        cache-enabled: true

    # Run tests with detailed output
    - name: Run tests
      run: ./gradlew test --stacktrace --info --scan

    # Build project (without re-running tests)
    - name: Build with Gradle
      run: ./gradlew build -x test

    # Upload test reports (even if failed)
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ matrix.os }}
        path: |
          build/reports/tests/
          build/test-results/
        retention-days: 7

  # Dependency analysis (runs once after all builds complete)
  dependency-submission:
    runs-on: ubuntu-latest
    needs: build-and-test  # Depends on successful builds
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generate dependency graph
      uses: gradle/actions/dependency-submission@v4
