name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:  # Ручной запуск

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Полная история коммитов для корректной работы Gradle

    # Установка прав для Gradle Wrapper
    - name: Set execute permissions
      run: |
        chmod +x gradlew
        ls -la gradlew*  # Проверка прав

    # Проверка доступности Gradle
    - name: Verify Gradle
      run: ./gradlew --version

    # Установка JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    # Настройка Gradle с кешированием
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false
        cache-enabled: true

    # Запуск тестов с детализированным выводом
    - name: Run tests
      run: ./gradlew test --stacktrace --info --scan

    # Сборка проекта (без повторного запуска тестов)
    - name: Build with Gradle
      run: ./gradlew build -x test

    # Загрузка отчетов тестов (даже при падении)
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: |
          build/reports/tests/
          build/test-results/
        retention-days: 7

  # Анализ зависимостей
  dependency-submission:
    runs-on: ubuntu-latest
    needs: build-and-test  # Зависит от успешной сборки
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generate dependency graph
      uses: gradle/actions/dependency-submission@v4
